<?php

namespace CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends EntityRepository
{
    public function getSharedCalendar($id_user) {
        var_dump($id_user);
        $query = $this->getEntityManager()
                ->createQuery("
	            SELECT c 
                    FROM CalendarBundle:Calendar c
                    WHERE c.shared = :id"
        );
        $query->setParameter('id', $id_user);
        return $query->getResult();
    }
}
